name: Build docs and commit to build branch

on:
  push:
    branches:
      - master
      - develop

jobs:
    build:
        defaults:
            run:
                working-directory: docs
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install python dependencies
              run: pip install -r requirements.txt

            - name: Build and deploy
              run: mkdocs gh-deploy --force --remote-branch build/documentation
